[package]
name = "bifrost-common-constants"
version = "1.0.0"
description = "The common runtime constants for Bifrost"
authors = { workspace = true }
homepage = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
bp-core = { workspace = true }

[features]
default = ["std"]
std = ["bp-core/std"]
