[package]
name = "bifrost-dev-constants"
version = "1.0.0"
description = "The substrate runtime constants for Bifrost Node development"
authors = { workspace = true }
homepage = { workspace = true}
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
# Bifrost
bifrost-common-constants = { workspace = true }
bp-core = { workspace = true }

# Substrate
sp-core = { workspace = true }
frame-support = { workspace = true }
pallet-evm = { workspace = true }

[features]
default = ["std"]
std = [
	"pallet-evm/std",
	"sp-core/std",
	"frame-support/std"
]
