[package]
name = "bifrost-dev-constants"
version = "1.0.0"
description = "The substrate runtime constants for BIFROST Node development"
authors = ["bifrost-platform"]
homepage = "https://thebifrost.io"
edition = "2021"
license = "Unlicense"
repository = "https://github.com/bifrost-platform/bifrost-node"

[dependencies]
# Bifrost
bifrost-common-constants = { default-features = false, path = "../../common/constants" }
bp-core = { default-features = false, path = "../../../primitives/core" }

# Substrate
sp-core = { default-features = false, git = "https://github.com/bifrost-platform/substrate", branch = "bifrost-node-v1.1.3" }
frame-support = { default-features = false, git = "https://github.com/bifrost-platform/substrate", branch = "bifrost-node-v1.1.3" }
pallet-evm = { default-features = false, git = "https://github.com/bifrost-platform/frontier", branch = "bifrost-node-v1.1.3" }

[features]
default = ["std"]
std = [
	"pallet-evm/std",
	"sp-core/std",
	"frame-support/std"
]
